pull_request_rules:
  - name: Auto merge into main when CI passes
    conditions:
      - check-success=[lint, unit-test, integration-test]
      - base=main
      - head~=^feature_.*
    actions:
      merge:
        method: merge
