AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  haverhill_311_app

  SAM Template for haverhill_311_app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  proxyHost:
    Type: String
    Description: The Endpoint of your RDS Proxy
  username:
    Type: String
    Description: The connection Username for your DB or Cluster
  db:
    Type: String
    Description: The Name of your Database instance
    Default: mysql
  port:
    Type: String
    Description: Connection port number for your RDS Proxy
    Default: 3306
  region:
    Type: String
    Description: The AWS Region for your DB Proxy

Resources:
  PipelineFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: haverhill_311_pipeline/
      Handler: app.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: 311PipelineSchedule
            Description: Schedules execution of the Hverhill 311 ETL pipeline
            Enabled: True
      VpcConfig:
        SecurityGroupIds:
          - sg-0b419d108348c329b
        SubnetIds:
          - subnet-0408d2b368d189bfc
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource:
                - !Sub arn:aws:rds:us-east-2:361899811679:db-proxy:prx-08c1220060b8b94b7/postgres

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PipelineFunction:
    Description: "311PipelineFunction Lambda Function ARN"
    Value: !GetAtt PipelineFunction.Arn
  PipelineFunctionIamRole:
    Description: "Implicit IAM Role created for 311PipelineFunction function"
    Value: !GetAtt PipelineFunctionRole.Arn
