# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: haverhill 311 lambda ci

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
    - name: Lint
      run: |
        make lint
    - name: Unit test
      run: |
        make unit-tests
    - name: Integration test
      run: |
        make integration-tests
